### PR TITLE
Innitial commit

### PR DESCRIPTION
**Pull request by NazarBondarenkoQ**
Please check my code.

### CODE REVIEW

**Comment by MaryanaKravets** [comment]
Hey! I have some remarks:
1) Access to class and methods, fields can be more private; delete redundant field in UserList; box1,box2 can be converted to alocal variable
2) Semicolomn in Conditions is redundant
3) When you prints email of users which have the same login date, please add some whitespace
4) And most importantly you must have for each genre average tickets price(as Map), the same is for count movie by genre.

**Comment by NazarBondarenkoQ** [comment]
> Hey! I have some remarks:
> 
> 1. Access to class and methods, fields can be more private; delete redundant field in UserList; box1,box2 can be converted to alocal variable
> 2. Semicolomn in Conditions is redundant
> 3. When you prints email of users which have the same login date, please add some whitespace
> 4. And most importantly you must have for each genre average tickets price(as Map), the same is for count movie by genre.

Done

**Review by BogdanShulga — APPROVED** [review]
Code works good as expected, I have no remarks,  endorsed.

**Review by MaryanaKravets — APPROVED** [review]
Ok, I'm satisfied.

**Review by NickRbk — CHANGES_REQUESTED** [review]
- [x] If lamda with one parameter and you omit type you can skip paranthesis - `box -> box.stream()` instead of `(box) -> box.stream()`. You have this mistake multiple times in project

- [x] `filter(Thing -> Thing...` Thing is a variable name not a type, so follow java naming convention (e.g, `thing -> ...`). You have this mistake multiple times in project

- [x] `filter(Movie -> Movie.getGenre().toUpperCase().equals(genre.toUpperCase()))` There you can use method equalsIgnoreCase()

- [x] To avoid possible mistakes use `@FunctionalInterface` annotation in your func interfaces

**Comment by NazarBondarenkoQ** [comment]
> * [x]  If lamda with one parameter and you omit type you can skip paranthesis - `box -> box.stream()` instead of `(box) -> box.stream()`. You have this mistake multiple times in project
> * [x]  `filter(Thing -> Thing...` Thing is a variable name not a type, so follow java naming convention (e.g, `thing -> ...`). You have this mistake multiple times in project
> * [x]  `filter(Movie -> Movie.getGenre().toUpperCase().equals(genre.toUpperCase()))` There you can use method equalsIgnoreCase()
> * [x]  To avoid possible mistakes use `@FunctionalInterface` annotation in your func interfaces

Done

**Review by NickRbk — APPROVED** [review]

**Comment by NickRbk** [comment]
This fragment could confuse:
```
.filter(movie -> movie.getGenre()
.equalsIgnoreCase(genre))
.count() + movies1.stream()
```
This one is more readable:
```
.filter(movie -> movie.getGenre().equalsIgnoreCase(genre))
.count() + movies1.stream()
```

**Pull request merged**
